# Generated by Django 6.0.1 on 2026-01-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date',
            new_name='annee',
        ),
        migrations.AddField(
            model_name='article',
            name='auteur',
            field=models.CharField(default='inconnu', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='genre',
            field=models.CharField(default='non specifié', max_length=50),
        ),
    ]
