# Generated by Django 6.0.1 on 2026-01-16 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_date_article_annee_article_auteur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='annee',
            new_name='date',
        ),
    ]
