# Generated by Django 6.0.1 on 2026-01-16 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_annee_article_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='article',
            name='telecharges_par',
            field=models.ManyToManyField(blank=True, related_name='articles_telecharges', to=settings.AUTH_USER_MODEL),
        ),
    ]
