# Generated by Django 6.0.1 on 2026-01-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_fichier_article_telecharges_par'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='books/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='genre',
            field=models.CharField(default='non spécifié', max_length=50),
        ),
    ]
